const PDFDocument = require("pdfkit");
const {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  ShadingType,
} = require("docx");

function safeName(s) {
  return String(s ?? "").replace(/[^\w.-]+/g, "_").slice(0, 80);
}

function buildExecutivePdf(alert, report) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 54, size: "A4" });
    const chunks = [];
    doc.on("data", (c) => chunks.push(c));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    const sev = report.severity_label || "HIGH";
    const generatedAt = new Date().toUTCString();

    doc.fontSize(10).fillColor("#64748b").text("AUTHGRAPH ITDR · EXECUTIVE INCIDENT BRIEF", { align: "left" });
    doc.moveDown(0.4);
    doc.fontSize(20).fillColor("#0f172a").text(report.subject || `${alert.attack} — ${alert.user} → ${alert.target}`);
    doc.moveDown(0.3);
    doc.fontSize(10).fillColor("#64748b")
      .text(`Incident ${alert.id} · ${generatedAt} · Severity ${sev} · Risk ${alert.risk ?? "—"}/100`);
    doc.moveDown(1);

    const section = (title, body) => {
      doc.fontSize(11).fillColor("#475569").text(title.toUpperCase(), { characterSpacing: 0.5 });
      doc.moveDown(0.25);
      doc.fontSize(11).fillColor("#1e293b").text(body || "—", { align: "justify", lineGap: 3 });
      doc.moveDown(0.8);
    };

    section("Executive summary", report.executive_summary);
    section("Technical summary", report.technical_summary);
    section("MITRE ATT&CK", `${report.mitre?.id || alert.mitre} ${report.mitre?.name || alert.attack} (${(report.mitre?.tactics || []).join(", ")})`);
    section("Blast radius", report.blast_radius);
    section("Risk rationale", report.risk_rationale);

    doc.fontSize(11).fillColor("#475569").text("AFFECTED IDENTITIES");
    doc.moveDown(0.3);
    for (const id of report.affected_identities || []) {
      doc.fontSize(10).fillColor("#1e293b").text(`• [${id.role}] ${id.name} — ${id.detail}`);
    }
    doc.moveDown(0.6);

    doc.fontSize(11).fillColor("#475569").text("EVIDENCE");
    doc.moveDown(0.3);
    for (const e of report.evidence_highlights || []) {
      doc.fontSize(10).fillColor("#1e293b").text(`• ${e}`);
    }
    doc.moveDown(0.6);

    doc.fontSize(11).fillColor("#475569").text("RECOMMENDED ACTIONS");
    doc.moveDown(0.3);
    for (const a of report.recommended_actions || []) {
      doc.fontSize(10).fillColor("#1e293b")
        .text(`${a.priority}. ${a.action} (${a.owner}) — ${a.rationale || ""}`);
    }
    doc.moveDown(0.6);

    if (report.indicators_of_compromise?.length) {
      section("Indicators of compromise", report.indicators_of_compromise.join(" · "));
    }
    if (report.false_positive_notes) {
      section("False positive notes", report.false_positive_notes);
    }

    doc.fontSize(8).fillColor("#94a3b8")
      .text("Generated by ARIA · AuthGraph ITDR · deepseek/deepseek-v4-pro", { align: "center" });
    doc.end();
  });
}

function cell(text, opts = {}) {
  return new TableCell({
    width: opts.width ? { size: opts.width, type: WidthType.PERCENTAGE } : undefined,
    shading: opts.header ? { fill: "1e293b", type: ShadingType.CLEAR } : undefined,
    children: [
      new Paragraph({
        children: [
          new TextRun({
            text: String(text ?? ""),
            bold: Boolean(opts.header),
            color: opts.header ? "FFFFFF" : "1e293b",
            size: opts.header ? 20 : 22,
          }),
        ],
      }),
    ],
  });
}

async function buildExecutiveDocx(alert, report) {
  const sev = report.severity_label || "HIGH";
  const generatedAt = new Date().toUTCString();

  const children = [
    new Paragraph({
      children: [new TextRun({ text: "AUTHGRAPH ITDR", bold: true, color: "475569", size: 18 })],
    }),
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: "Executive Incident Brief", bold: true, size: 36 })],
    }),
    new Paragraph({
      children: [new TextRun({ text: report.subject || `${alert.attack} — ${alert.target}`, size: 24, color: "334155" })],
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Incident ${alert.id} · ${generatedAt} · ${sev} · Risk ${alert.risk ?? "—"}/100 · MITRE ${report.mitre?.id || alert.mitre}`,
          size: 20,
          color: "64748b",
        }),
      ],
    }),
    new Paragraph({ text: "" }),
    heading("Executive summary"),
    body(report.executive_summary),
    heading("Technical summary"),
    body(report.technical_summary),
    heading("Blast radius"),
    body(report.blast_radius),
    heading("Risk rationale"),
    body(report.risk_rationale),
    heading("Affected identities"),
    identityTable(report.affected_identities || []),
    heading("Evidence highlights"),
    bullets(report.evidence_highlights || []),
    heading("Recommended actions"),
    actionsTable(report.recommended_actions || []),
  ];

  if (report.indicators_of_compromise?.length) {
    children.push(heading("Indicators of compromise"), bullets(report.indicators_of_compromise));
  }
  if (report.false_positive_notes) {
    children.push(heading("False positive notes"), body(report.false_positive_notes));
  }

  children.push(
    new Paragraph({ text: "" }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [
        new TextRun({
          text: "Generated by ARIA · AuthGraph ITDR · deepseek/deepseek-v4-pro",
          size: 18,
          color: "94a3b8",
          italics: true,
        }),
      ],
    }),
  );

  const doc = new Document({
    sections: [{ properties: {}, children }],
  });
  return Packer.toBuffer(doc);
}

function heading(text) {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 240, after: 120 },
    children: [new TextRun({ text, bold: true, size: 24, color: "334155" })],
  });
}

function body(text) {
  return new Paragraph({
    spacing: { after: 160 },
    children: [new TextRun({ text: String(text || "—"), size: 22 })],
  });
}

function bullets(items) {
  return items.map(
    (item) =>
      new Paragraph({
        bullet: { level: 0 },
        spacing: { after: 80 },
        children: [new TextRun({ text: String(item), size: 22 })],
      }),
  );
}

function identityTable(rows) {
  if (!rows.length) return body("—");
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({ children: [cell("Role", { header: true, width: 18 }), cell("Identity", { header: true, width: 32 }), cell("Detail", { header: true, width: 50 })] }),
      ...rows.map(
        (r) =>
          new TableRow({
            children: [cell(r.role, { width: 18 }), cell(r.name, { width: 32 }), cell(r.detail, { width: 50 })],
          }),
      ),
    ],
  });
}

function actionsTable(actions) {
  if (!actions.length) return body("—");
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        children: [
          cell("#", { header: true, width: 8 }),
          cell("Action", { header: true, width: 42 }),
          cell("Owner", { header: true, width: 15 }),
          cell("Rationale", { header: true, width: 35 }),
        ],
      }),
      ...actions.map(
        (a) =>
          new TableRow({
            children: [
              cell(String(a.priority), { width: 8 }),
              cell(a.action, { width: 42 }),
              cell(a.owner, { width: 15 }),
              cell(a.rationale, { width: 35 }),
            ],
          }),
      ),
    ],
  });
}

function exportFilename(alert, format) {
  const attack = safeName(alert.attack || "incident");
  const date = new Date().toISOString().slice(0, 10);
  return `AuthGraph-ITDR-${attack}-${date}.${format}`;
}

module.exports = {
  buildExecutivePdf,
  buildExecutiveDocx,
  exportFilename,
};
